# Generated by Django 2.2.5 on 2019-09-23 18:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipos',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=50, size=None),
        ),
    ]
